INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88854607/','Piso en paseo de la Republica Dominicana, Parla Este, Parla','156000','3','93 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87707905/','Chalet adosado en calle Lago de Bañolas, Laguna Park, Parla','289900','5','228 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87676163/','Chalet en calle San Martín de la Vega, Getafe Centro, Getafe','759500','5','600 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88749052/','Piso en calle Jerusalén, Parque Inlasa, Parla','113500','3','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88521792/','Piso en calle Alfonso XIII, Reyes, Parla','95000','3','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88405680/','Piso en calle del Rio Jordan, Parque Inlasa, Parla','92500','3','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88007706/','Piso en calle del Olvido, Calle Pinto-San Roque, Parla','154500','3','100 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87174312/','Piso en calle el Cebadero, El Nido-Las Fuentes, Parla','239000','4','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86276341/','Piso en calle Pablo Gargallo, Fuentebella-San Felix-El Leguario, Parla','164500','3','153 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/84631750/','Chalet adosado en calle Goya, Pintores-Ferial, Parla','179500','4','160 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/81939285/','Casa o chalet independiente en calle de la Sal, Centro, Parla','375000','4','480 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88588578/','Piso en calle la Pila, El Nido-Las Fuentes, Parla','113500','1','62 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88503797/','Dúplex en avenida Salvador Allende, San Nicasio, Leganés','478000','5','245 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/82554625/','Dúplex en calle Domingo Malagón, Centro, Parla','174500','3','130 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89078278/','Chalet adosado en avenida del Leguario, Fuentebella-San Felix-El Leguario, Parla','245000','4','208 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87205095/','Chalet adosado en VITORIA, La Serna, Fuenlabrada','389900','4','299 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86548679/','Piso en El Naranjo, Fuenlabrada','164000','3','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/82955379/','Piso en Universidad - Hospital, Fuenlabrada','265000','4','120 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89033999/','Piso en calle la Pila, El Nido-Las Fuentes, Parla','199500','4','100 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88993780/','Piso en calle Lugo, Las Dehesillas-Vereda de los Estudiantes, Leganés','219500','3','120 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88919878/','Piso en avenida de las Estrellas, Parla Este, Parla','169000','3','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87727041/','Chalet adosado en calle Delicias, Pintores-Ferial, Parla','109900','3','95 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85231773/','Chalet en calle Empedrado, Centro, Parla','249900','3','164 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/83243355/','Piso en Norte - Universidad, Móstoles','165000','3','91 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88446274/','Piso en calle de Jerico, Parque Inlasa, Parla','99900','3','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88996490/','Piso en calle del Planeta Urano, Parla Este, Parla','174900','3','104 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85942230/','Ático en calle las Camelias, Valderas - Los Castillos, Alcorcón','420000','3','132 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88992845/','Piso en calle del Pilar, Centro, Móstoles','124000','2','76 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88977275/','Piso en calle del Pilar, Centro, Móstoles','63000','1','37 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88966575/','Piso en Ciudad Real, Villayuventus-Renfe, Parla','120000','2','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88688222/','Piso en calle Lago Blanco, Laguna Park, Parla','177000','3','80 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89034099/','Piso en calle Madrid, 46, Getafe Centro, Getafe','180000','1','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89103702/','Casa o chalet independiente en avenida de Islandia, s/n, Zona Europa, Arroyomolinos','396000','4','240 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88904639/','Piso en calle Alfonso XIII, Reyes, Parla','85000','3','91 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88889489/','Piso en calle San Antón, Villayuventus-Renfe, Parla','69000','2','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88655651/','Piso en calle Lago Blanco, Laguna Park, Parla','170000','3','109 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87859506/','Piso en calle Jericó, Parque Inlasa, Parla','110000','3','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87806992/','Piso en calle Carolina Coronado, Centro, Parla','170000','3','107 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87390419/','Piso en GARDENIAS, Universidad - Hospital, Fuenlabrada','289000','3','139 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88723577/','Piso en calle Cipriano Diaz el Herrero, s/n, El Rosón - Kelvinator, Getafe','247000','2','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88061117/','Casa o chalet independiente en Coimbra - Guadarrama, Móstoles','469000','5','469 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88055921/','Piso en calle Cipriano Diaz el Herrero, s/n, El Rosón - Kelvinator, Getafe','227000','2','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88808499/','Piso en calle Cipriano Diaz el Herrero, s/n, El Rosón - Kelvinator, Getafe','254000','2','86 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88859872/','Piso en calle Reina Victoria, Reyes, Parla','126000','4','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88758891/','Piso en plaza Sierra de Cruz Verde, Zona Centro Joven, Alcorcón','114900','2','60 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88648256/','Piso en Juan de la Cierva, Getafe','119500','3','68 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88686458/','Piso en Villayuventus-Renfe, Parla','92000','3','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88891207/','Piso en La Alhóndiga, Getafe','109000','2','68 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88785573/','Piso en Centro, Fuenlabrada','176000','3','80 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88712480/','Piso en Centro, Fuenlabrada','191000','2','116 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88483616/','Piso en Fuenlabrada II - El Molino, Fuenlabrada','145000','3','80 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87956698/','Casa o chalet independiente en avenida de Islandia, s/n, Zona Europa, Arroyomolinos','451000','5','332 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88778130/','Chalet adosado en Los Molinos, Getafe','495000','4','213 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88758934/','Piso en calle de los Angeles, Centro, Fuenlabrada','118000','3','96 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88176301/','Piso en Calle Pinto-San Roque, Parla','89990','3','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88886337/','Piso en Norte - Universidad, Móstoles','231000','3','124 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88714785/','Piso en Universidad, Getafe','158000','4','95 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89026635/','Chalet en Parque Ondarreta - Urtinsa, Alcorcón','370000','3','160 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88603521/','Piso en Casco Antiguo, Alcorcón','120000','2','62 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89087563/','Chalet en Parque Ondarreta - Urtinsa, Alcorcón','366000','3','160 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89087562/','Chalet en Parque Ondarreta - Urtinsa, Alcorcón','368000','3','160 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88640647/','Piso en Centro, Móstoles','159000','1','50 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/82381797/','Casa o chalet independiente en Hispanoamérica - Comunidades, Valdemoro','665000','4','465 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86258592/','Piso en calle Oslo, s/n, Parque oeste - Fuente Cisneros, Alcorcón','299000','2','108 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86258585/','Piso en calle Oslo, s/n, Parque oeste - Fuente Cisneros, Alcorcón','274000','2','97 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86258590/','Piso en calle Oslo, s/n, Parque oeste - Fuente Cisneros, Alcorcón','204000','1','60 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88691831/','Chalet adosado en puerta del sol, Sector 3, Getafe','421000','6','252 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87443805/','Casa o chalet independiente en calle de la Estación, Griñón','399000','6','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87159994/','Chalet adosado en calle Villa Adriana, Fuenlabrada II - El Molino, Fuenlabrada','319000','5','220 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88758793/','Piso en CIUDADES, Parque Inlasa, Parla','92000','3','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86763697/','Casa o chalet independiente en Coimbra - Guadarrama, Móstoles','469000','5','335 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88881102/','Ático en calle los Arces, Prado de Santo Domingo, Alcorcón','310000','3','127 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88428568/','Chalet pareado en calle CORDOBA, Griñón','399000','5','472 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/81219800/','Chalet en Griñón','459000','7','543 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/37207287/','Casa o chalet independiente en calle Alcacel, Griñón','650000','6','680 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88733969/','Casa o chalet independiente en Griñón','270000','5','222 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87099797/','Piso en Humanes de Madrid','104260','3','84 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88454410/','Piso en calle de Andorra, Fuenlabrada II - El Molino, Fuenlabrada','158000','3','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86207167/','Casa o chalet independiente en avenida de Portugal, Zona Europa, Arroyomolinos','379500','4','253 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89024481/','Chalet adosado en Santoña, Las Castañeras - Bulevar, Arroyomolinos','319900','4','281 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88042625/','Chalet pareado en DINAMARCA, Zona Europa, Arroyomolinos','384900','3','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/84925377/','Chalet adosado en calle Río Manzanares, Casarrubuelos','187500','4','251 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/84586853/','Dúplex en COLONIA DE NUESTRA SEÑORA DE LORETO, Sector 3, Getafe','310000','4','150 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/82253067/','Ático en plaza San Juan, Centro, Parla','179900','2','92 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88557847/','Chalet en Coimbra - Guadarrama, Móstoles','570000','4','415 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88184437/','Chalet en Coimbra - Guadarrama, Móstoles','305000','4','277 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88871103/','Ático en juan de juanes, Norte - Universidad, Móstoles','365000','3','240 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88508997/','Chalet adosado en av cantabrico 68, Las Castañeras - Bulevar, Arroyomolinos','324900','4','180 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88481991/','Piso en calle de Fray Luis de Leon, Descubridores-Escritores, Leganés','115000','3','58 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88057108/','Chalet pareado en IRLANDA, Zona Europa, Arroyomolinos','365000','4','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927138/','Piso en Valderas - Los Castillos, Alcorcón','189000','3','78 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88844242/','Piso en Humanes de Madrid','146000','3','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88450547/','Chalet en La Cárcaba - El Encinar - Montemolinos, Arroyomolinos','324900','4','248 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88365158/','Chalet en Zona el Caño, Arroyomolinos','339900','3','257 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88341614/','Chalet en Zona Europa, Arroyomolinos','820000','4','492 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88087832/','Piso en calle Sur, San José - Buenos Aires, Pinto','205000','3','114 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86274583/','Chalet en La Cárcaba - El Encinar - Montemolinos, Arroyomolinos','289000','5','241 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88553434/','Piso en calle Berardo Martin, 3, Este, Móstoles','185000','4','90 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88504735/','Chalet pareado en acebo, Coimbra - Guadarrama, Móstoles','335000','4','260 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87610926/','Ático en del pintor picasso, Norte - Universidad, Móstoles','415000','4','240 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/81146222/','Chalet pareado en peñiscola, 1, Urbanización Mediterráneo, Arroyomolinos','335000','4','216 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/82602701/','Piso en calle Pintor Velazquez, Móstoles, Norte - Universidad, Móstoles','235000','3','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88953308/','Chalet adosado en Zona Europa, Arroyomolinos','314900','3','300 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88230215/','Piso en avenida Abogados de Atocha, 4, Norte - Universidad, Móstoles','344500','3','129 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88230217/','Dúplex en avenida Abogados de Atocha, 4, Norte - Universidad, Móstoles','464000','4','206 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927179/','Dúplex en plaza de España, Torrejón de la Calzada','169000','3','98 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88315634/','Piso en madrid, Getafe Centro, Getafe','279000','5','150 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88002821/','Chalet pareado en calle Zurbarán, Torrejón de la Calzada','248560','4','233 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87484869/','Chalet adosado en calle Roble, Torrejón de la Calzada','266240','4','220 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87264185/','Chalet pareado en calle Granada, Torrejón de la Calzada','290000','4','265 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88932149/','Chalet adosado en Norte - Universidad, Móstoles','415000','3','220 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87894618/','Chalet adosado en paseo del arroyo., Coimbra - Guadarrama, Móstoles','273900','3','243 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87889101/','Piso en calle Lago Tiberíades, Parque Inlasa, Parla','139900','3','90 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87774649/','Piso en calle de Móstoles, El Naranjo, Fuenlabrada','151260','3','78 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87264383/','Chalet adosado en calle Benito Pérez Galdós, Torrejón de la Calzada','380000','5','303 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86227182/','Chalet adosado en paseo del arroyo, Coimbra - Guadarrama, Móstoles','259900','5','270 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86705453/','Piso en Concepción, Getafe Centro, Getafe','265000','3','94 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88905006/','Piso en Valderas - Los Castillos, Alcorcón','152000','3','73 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87900411/','Piso en Norte - Universidad, Móstoles','98000','3','60 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86787500/','Piso en calle Peñuelas, 1, Torrejón de la Calzada','148000','3','107 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88450449/','Piso en Norte - Universidad, Móstoles','133000','2','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89052114/','Piso en calle Jeromín, Casco Antiguo, Leganés','299700','4','152 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88690558/','Chalet adosado en Las Américas, Parla','317990','4','206 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86991430/','Chalet adosado en Parla Este, Parla','388000','4','270 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88838182/','Chalet pareado en Griñón','380000','5','390 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/1043105/','Piso en Loranca, Fuenlabrada','189990','3','105 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/83661738/','Piso en La Serna, Fuenlabrada','155000','3','87 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/81414108/','Casa o chalet independiente en Griñón','350000','4','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/39552635/','Chalet pareado en Griñón','308000','3','220 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87789891/','Piso en monegros, Zarzaquemada, Leganés','169000','3','88 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89118407/','Piso en Tarragona, Juan de la Cierva, Getafe','138000','2','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88602706/','Piso en Casco Antiguo - La Dehesa - Los Monteros, Arroyomolinos','174500','2','82 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85945148/','Chalet en Leganés norte, Leganés','499990','4','330 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88217483/','Piso en Centro, Fuenlabrada','146000','3','72 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88150362/','Piso en Sur, Móstoles','129900','3','80 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87968418/','Piso en Este, Móstoles','129900','3','74 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86411690/','Piso en Centro, Móstoles','145000','3','86 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89138917/','Chalet adosado en Perales del Rio, Getafe','369000','4','290 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89050053/','Chalet pareado en La Cárcaba - El Encinar - Montemolinos, Arroyomolinos','469900','4','360 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89142388/','Piso en calle Reyes Católicos, Reyes, Parla','127000','3','81 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89129978/','Piso en calle del Planeta Saturno, Parla Este, Parla','230000','4','135 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89146801/','Piso en calle San Jose, Centro, Fuenlabrada','132000','3','67 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86497899/','Piso en Centro, Fuenlabrada','123000','3','90 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88922989/','Casa o chalet independiente en ALCALDES, 6, Batres','235000','4','222 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89136211/','Chalet adosado en Urbanización Mediterráneo, Arroyomolinos','310000','4','255 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89076268/','Piso en calle la Huerta, Casco Antiguo, Alcorcón','90000','3','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88693282/','Piso en calle de las Ciudades, Villayuventus-Renfe, Parla','92000','3','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85680176/','Chalet en paseo del Arroyo, 34, Coimbra - Guadarrama, Móstoles','277000','5','270 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89129591/','Piso en calle San Félix, Calle Pinto-San Roque, Parla','121000','2','92 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89142694/','Piso en Lago Tiberiades, s/n, La Ermita, Parla','49000','2','64 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927632/','Chalet en calle las Palomas, Griñón','299500','4','343 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88784537/','Piso en calle Islas Medas, Humanes de Madrid','207500','3','114 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87786203/','Piso en calle de Pablo VI, Pintores-Ferial, Parla','93500','3','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87191908/','Casa o chalet independiente en avenida del Castillo, Campodón - Ventorro del Cano, Alcorcón','495000','4','495 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88369206/','Chalet en Altos del Olivar - El Caracol, Valdemoro','356000','6','268 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85529077/','Piso en Cuevas - Ilustración, Ciempozuelos','85000','1','50 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89111356/','Piso en Teneria i - Teneria Ii, Pinto','239900','3','145 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89094397/','Chalet en Perales del Rio, Getafe','250000','4','139 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85864022/','Chalet en calle Agustina de Aragón, Hospital, Valdemoro','249000','3','147 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89057790/','Chalet adosado en calle de los fresnos, Coimbra - Guadarrama, Móstoles','278000','5','210 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89052203/','Piso en Prado de Santo Domingo, Alcorcón','292000','3','98 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88977017/','Piso en calle de Jerico, 21, Parque Inlasa, Parla','116600','2','65 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88669664/','Chalet adosado en calle calpe, s/n, Urbanización Mediterráneo, Arroyomolinos','309900','4','334 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86565450/','Piso en calle Españoleto, Pintores-Ferial, Parla','90000','3','79 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88945262/','Chalet en La Ermita, Parla','329500','5','269 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88909077/','Chalet en Coimbra - Guadarrama, Móstoles','259500','5','189 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88876945/','Piso en San Nicasio, Leganés','137500','3','76 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88835505/','Chalet en Las Américas, Parla','280000','5','170 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86222114/','Chalet en Perales del Rio, Getafe','199000','3','113 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88797712/','Piso en Brezo, Valdemoro','164000','2','90 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86255404/','Piso en Centro, Fuenlabrada','117000','3','79 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88729706/','Chalet en Perales del Rio, Getafe','249000','3','139 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88638504/','Chalet en Zona el Caño, Arroyomolinos','406000','5','313 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88585535/','Piso en Este, Móstoles','157000','3','83 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88507001/','Chalet en El Soto - Coveta, Móstoles','370000','5','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87123543/','Piso en Villayuventus-Renfe, Parla','93000','3','83 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88482816/','Piso en San José - Buenos Aires, Pinto','129900','2','61 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88278099/','Chalet en San Isidro, Getafe','299000','3','230 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88190300/','Chalet en Pintores-Ferial, Parla','297000','6','237 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88060598/','Piso en El Carrascal, Leganés','275000','3','127 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88021290/','Piso en Puerta Pinto - Valparaíso, Pinto','198900','3','95 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87937579/','Ático en Getafe Centro, Getafe','475000','5','241 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87827979/','Piso en Centro - Ayuntamiento, Pinto','290000','4','118 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87786795/','Chalet en Altos del Olivar - El Caracol, Valdemoro','275000','4','257 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87772083/','Ático en El Bercial, Getafe','398000','3','148 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87609475/','Casa o chalet independiente en Coimbra - Guadarrama, Móstoles','253000','2','280 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87593504/','Chalet en Cubas de la Sagra','243000','5','225 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87539478/','Piso en calle Sierra de Albarracín, Zona Centro Joven, Alcorcón','124000','3','55 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87536743/','Chalet en Centro, Valdemoro','385000','4','236 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87514022/','Chalet en Serranillos del Valle','179500','4','160 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87514001/','Piso en Zona Renfe, Alcorcón','120000','2','62 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87475086/','Piso en Zarzaquemada, Leganés','160000','3','79 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87442698/','Piso en Altos del Olivar - El Caracol, Valdemoro','189000','3','131 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87194026/','Chalet en Reyes, Parla','295500','5','261 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87145673/','Chalet en Cuevas - Ilustración, Ciempozuelos','239000','5','273 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87058559/','Chalet en Altos del Olivar - El Caracol, Valdemoro','268000','4','279 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86773218/','Piso en Prado de Santo Domingo, Alcorcón','298000','3','112 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86508597/','Dúplex en Griñón','149500','2','87 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86296131/','Chalet en Solagua, Leganés','470000','3','139 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86006153/','Dúplex en Restón i - Restón Ii, Valdemoro','209000','2','170 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85976120/','Chalet en Campodón - Ventorro del Cano, Alcorcón','950000','6','722 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85917432/','Piso en Norte - Universidad, Móstoles','130900','1','76 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85837263/','Piso en Puerta Pinto - Valparaíso, Pinto','239900','3','90 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85833764/','Chalet en Urbanización Mediterráneo, Arroyomolinos','349900','5','295 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85742566/','Piso en Getafe Centro, Getafe','289000','3','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89046208/','Chalet pareado en calle de las Encinas, Coimbra - Guadarrama, Móstoles','285000','4','223 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88885148/','Piso en plaza de la Hispanidad, 9, Casco Antiguo, Alcorcón','155000','4','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88888038/','Piso en calle el Charco, Casco Antiguo, Leganés','205000','4','108 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88870752/','Piso en calle Eugenio Serrano, La Alhóndiga, Getafe','102000','3','67 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88784724/','Piso en calle de Cuenca, Villayuventus-Renfe, Parla','108000','3','88 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88695474/','Piso en calle Eugenio Serrano, La Alhóndiga, Getafe','102000','3','67 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88435110/','Chalet adosado en calle Benito Pérez Galdós, Torrejón de la Calzada','240363','3','180 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87887338/','Chalet adosado en calle Manuel Fraga Iribarne, 26, Torrejón de la Calzada','296000','4','253 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87235573/','Chalet adosado en calle Manuel Fraga Iribarne, 24, Torrejón de la Calzada','296000','4','253 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86716967/','Piso en calle Alfonso X el Sabio, Reyes, Parla','115000','3','71 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89111338/','Piso en calle Planeta Neptuno, Parla Este, Parla','179000','4','110 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89030360/','Chalet pareado en calle Garcilaso de la Vega, Cubas de la Sagra','465000','3','285 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/89024714/','Chalet en calle Aranjuez, Moraleja de Enmedio','248000','3','150 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88993218/','Chalet pareado en calle Zurbarán, Torrejón de la Calzada','295000','4','278 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88991989/','Piso en paseo Granados, El Arroyo - La Fuente, Fuenlabrada','129900','4','85 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88957744/','Piso en El Naranjo, Fuenlabrada','169000','3','98 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88194857/','Piso en La Avanzada - La Cueva, Fuenlabrada','118440','3','77 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88014507/','Piso en Fuenlabrada, San Isidro, Getafe','244900','3','96 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88874953/','Piso en calle Pablo Casals, Fuentebella-San Felix-El Leguario, Parla','109900','3','75 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88973664/','Piso en avenida de las Ciudades, Juan de la Cierva, Getafe','139900','3','70 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88829905/','Chalet pareado en huerta del cura, 23, Moraleja de Enmedio','325000','4','154 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88719432/','Casa o chalet independiente en calle del Tejo, Coimbra - Guadarrama, Móstoles','386000','4','297 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86528631/','Chalet adosado en paseo del Arroyo, Coimbra - Guadarrama, Móstoles','288900','4','208 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86140628/','Casa o chalet independiente en calle de los Fresnos, Coimbra - Guadarrama, Móstoles','530644','6','367 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/86135416/','Chalet adosado en paseo del Arroyo, Coimbra - Guadarrama, Móstoles','275000','3','256 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88931529/','Piso en calle Fuente Cisneros, Parque oeste - Fuente Cisneros, Alcorcón','252000','2','103 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88964659/','Piso en Paraguay, V Centenario, Leganés','257000','4','112 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927182/','Casa o chalet independiente en avenida de la Paz, Griñón','629000','4','394 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927166/','Chalet en calle Illescas, Restón i - Restón Ii, Valdemoro','250000','4','198 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88927135/','Chalet en calle de Brasil, Hispanoamérica - Comunidades, Valdemoro','279000','3','198 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88905248/','Piso en avenida de María Guerrero, Leganés norte, Leganés','354000','4','150 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88856153/','Piso en calle Copenhague, Parque oeste - Fuente Cisneros, Alcorcón','399000','3','118 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88813127/','Chalet pareado en calle Zamora, Torrejón de la Calzada','270000','5','239 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/84423525/','Chalet en calle Carmen Martin Gaite, Hospital, Valdemoro','280000','4','338 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/85864746/','Piso en paseo de Goya, Norte - Universidad, Móstoles','160000','4','95 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88747739/','Chalet adosado en calle Benito Pérez Galdós, Torrejón de la Calzada','372000','6','354 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88715207/','Chalet en calle Copenhague, Parque oeste - Fuente Cisneros, Alcorcón','460000','5','194 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88592808/','Casa o chalet independiente en paseo del Carraperal, Griñón','350000','4','258 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88584778/','Casa o chalet independiente en calle de las Higueras, Serranillos del Valle','319000','4','306 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88584794/','Chalet adosado en calle Federico Moreno Torroba, Torrejón de Velasco','245000','4','204 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88380915/','Chalet en calle Bahamas, Hispanoamérica - Comunidades, Valdemoro','295000','3','258 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88268031/','Casa o chalet independiente en calle Llanillos, Cubas de la Sagra','375000','8','293 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88188154/','Chalet adosado en calle Rosalía de Castro, Torrejón de la Calzada','295500','5','207 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88116212/','Piso en calle Peñuelas, Torrejón de la Calzada','153000','3','101 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88007810/','Chalet en calle Málaga, Griñón','474400','5','354 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/88006352/','Chalet en calle de Arcadia, Restón i - Restón Ii, Valdemoro','269000','4','162 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87787828/','Piso en Rioja, Zarzaquemada, Leganés','144900','3','76 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/84946761/','Casa o chalet independiente en paseo de la Salle, Griñón','460000','6','450 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87728972/','Chalet adosado en calle de Bilbao, Las Dehesillas-Vereda de los Estudiantes, Leganés','337000','4','313 ');
INSERT INTO pisos (URL,DIRECCION,PRECIO,HABITACIONES,TAMANO) VALUES ('https://www.idealista.com//inmueble/87569063/','Chalet adosado en calle Córdoba, Puerta Pinto - Valparaíso, Pinto','465000','5','404 ');